/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "bg-input": "rgba(244,246,249,.5)",
        "input-border": "rgba(28,73,128,.1)",
        "left-border": "rgba(39,73,125,.5)",
        "host-btn": "#1C4980",
        "login-btn": "#0073e6",
        featured: "linear-gradient(180deg,#F5FAFE 0%,#FFFFFF 100%)",
        "border-color": "#DDE5EA",
        arrow: "#E5F1FC",
        fe: "#fff0c2",
        "text-color": "#d77b35",
        "circle-two": "#F8ECEA",
        "text-two": "#c85b50",
        "circle-three": "#EAEDF1",
        "text-four": "#6049e4",
        "circle-four": "#EAE8FB",
        "text-five": "#4aa46d",
        "circle-five": "#EBFEF5",
        "text-six": "#3171de",
        "circle-six": "#D7E8FE",
        "mentor-text": "#966d00",
        "prac-text": "#562f95",
        "learn-text": "#154177",
        "footer-bg": "#153460",
        "button-bg": "#DADCE0",
        "footer-button": "#245DB0",
        "footer-text": "#ffffffb3",
      },
      scale: {
        175: "3",
        4: "4",
        5: "5",
      },
      height: {
        80: "80vh",
      },
      fontFamily: {
        inter: "Inter, sans-serif",
      },
      fontSize: {
        sm: "0.8rem",
        base: "1rem",
        xl: "1.25rem",
        "2xl": "1.563rem",
        "3xl": "1.953rem",
        "4xl": "2.441rem",
        "5xl": "3.052rem",
        40: "40px",
        50: "50px",
        54: "54px",
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        DEFAULT: "4px",
        md: "0.375rem",
        lg: "0.5rem",
        full: "9999px",
        large: "12px",
        28: "34px",
      },
    },
  },
  plugins: [],
};
